In [1]:
import pandas as pd
import numpy as np
import random
import glob
import csv, os

In [2]:
def is_file_empty(file_path):
    return os.path.exists(file_path) and os.stat(file_path).st_size == 0

In [3]:
count = 0
df = pd.DataFrame()
for files in glob.glob('C:\\Users\\HARIKA\\Desktop\\DataScience_2019501065\\DADV_FinalExam\\Assignments\\Assignment2\\*.csv'):
    if count == 30:
        break
    f=open(files, 'r')
    name = os.path.basename(f.name).replace(".csv","")
    if is_file_empty("C:\\Users\\HARIKA\\Desktop\\DataScience_2019501065\\DADV_FinalExam\\Assignments\\Assignment2\\"+name+".csv"):
        continue
    data = pd.read_csv(f)
    gain = (data.at[data.shape[0]-1, "Close Price"] / data.at[0,"Close Price"]) - 1
#     gain = (close[len(close)-1]/close[0])-1
    row = {'Code': name, 'Gain': gain}
    df = df.append(row, ignore_index=True)
    count = count + 1
    f.close()
print("done")

done

In [4]:
df

      Code       Gain
0   500023   0.837194
1   500087  -0.211315
2   503624  26.051852
3   507514   5.018605
4   509480  -0.678260
5   511147   0.826667
6   512291   0.052632
7   513295   2.964072
8   514144   5.796296
9   519421  -0.700829
10  521068  -0.541869
11  521232   2.107280
12  523222   2.223214
13  524558  -0.303423
14  524580   2.401575
15  524804  -0.113938
16  526095   0.445087
17  530965   3.843548
18  531099  -0.377119
19  531112  -0.602390
20  531402  -0.309859
21  531996   1.841270
22  532005   0.005025
23  532918  -0.574809
24  537254   3.782097
25  538891   0.426460
26  539113   2.011167
27  539196  10.879195
28  540150  -0.188940
29  541627  -0.296835

In [5]:
df = df.sort_values("Gain", ascending=False)
df.head(10)

      Code       Gain
2   503624  26.051852
27  539196  10.879195
8   514144   5.796296
3   507514   5.018605
17  530965   3.843548
24  537254   3.782097
7   513295   2.964072
14  524580   2.401575
12  523222   2.223214
11  521232   2.107280
26  539113   2.011167
21  531996   1.841270
0   500023   0.837194
5   511147   0.826667
16  526095   0.445087
25  538891   0.426460
6   512291   0.052632
22  532005   0.005025
15  524804  -0.113938
28  540150  -0.188940
1   500087  -0.211315
29  541627  -0.296835
13  524558  -0.303423
20  531402  -0.309859
18  531099  -0.377119
10  521068  -0.541869
23  532918  -0.574809
19  531112  -0.602390
4   509480  -0.678260
9   519421  -0.700829

In [6]:
icici = pd.read_csv("icici.csv")

FileNotFoundError: [Errno 2] File icici.csv does not exist: 'icici.csv'

In [ ]:
dic = {}
count = 1
for files in glob.glob("E:\\DADV\\BSE-Assignment\\Datasets\\*.csv"):
    f=open(files, 'r')
    if count == 10:
        break
    name = os.path.basename(f.name).replace(".csv","")
    if is_file_empty("E:\\DADV\\BSE-Assignment\\Datasets\\"+name+".csv"):
        continue
    data = pd.read_csv(f)
    dic[name] = list(data["Close Price"])
    count = count + 1
    f.close()

#making all equal sized lists (for correlation to happen)
dic["icici"] = list(icici["Close Price"])
max_length = 0
for lis in dic.values():
    max_length = max(max_length, len(lis))
for lis in dic.values():
    lis += [0.0] * (max_length - len(lis))

#finding the correlation
df = pd.DataFrame()
for each1 in dic.keys():
    corr = np.corrcoef(dic.get("icici"), dic.get(each1))[0][1]
    row = {'Code': each1, 'Corr': corr}
    df = df.append(row, ignore_index=True)
df

In [ ]:
df = df.sort_values("Corr", ascending=False)
df